version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    update:
      strategy: "widen"
    labels:
      - "dependencies"
    automerged:
      enabled: true
      commit-message: "Automatic dependency update"
      merge-method: "squash"
